"""Lib de langue pour l'interface graphique de SigAnTo"""

def get_fra_lib():
    # load FR
    fra_lib = {
        "siganto": "SigAnTo : Outil d'analyse de signaux",
        "lang": "Français",
        "load": "Charger un fichier WAV / Rétablir le fichier WAV",
        "load_msg": "Charger un fichier WAV pour commencer l'analyse",
        "close": "Fermer le fichier WAV",
        "invalid_wav": "Fichier WAV invalide",
        "no_file": "Aucun fichier chargé",
        "encoding": "Encodage: ",
        "samples": "Echantillons: ",
        "sampling_frq": "Fréquence d'échantillonnage: ",
        "error": "Erreur",
        "apply": "Appliquer",
        "fin": "Fin",
        "duree": "Durée",
        "oui": "Oui",
        "non": "Non",
        "params": "Paramètres",
        "main_viz": "Spectrogrammes",
        "group_spec": "Groupe: Spectrogramme et DSP",
        "spec_dsp": "Spectrogramme et DSP",
        "group_const": "Groupe: Spectrogramme, Constellation, DSP max",
        "spec_const": "Spectrogramme, Constellation, DSP max",
        "spec_3d": "Spectrogramme 3D",
        "display": "Affichage",
        "frq_info": "Informations de fréquence/puissance/rapidité",
        "cursors_on": "Curseurs: ON",
        "cursors_off": "Curseurs: OFF",
        "clear_cursors": "Retirer curseurs",
        "modify": "Modifier",
        "move_frq": "Déplacer la fréquence centrale (valeurs)",
        "high_low": "Filtre passe-bas ou passe-haut",
        "low_val": "Bas",
        "high_val": "Haut",
        "freq_pass": "Fréquence de coupure (Hz) :",
        "filter_high_low": "Appliquer un filtre passe-haut/bas",
        "bandpass": "Filtre passe-bande",
        "filter_band": "Appliquer un filtre passe-bande",
        "freq_low": "Fréquence de coupure basse en Hz:",
        "freq_high": "Fréquence de coupure haute en Hz:",
        "freq_valid": "Entrez des fréquences de coupure valides",
        "mean": "Moyenner le signal",
        "mean_level": "Niveau moyen en dB: ",
        "level": "Niveau de moyennage: ",
        "apply_mean": "Appliquer le moyennage par défaut",
        "def_level": "Définir le seuil",
        "enter_level": "Entrer le niveau en dB :", 
        "downsample": "Sous-échantillonner",
        "down_value": "Entrez le taux de sous-échantillonnage (entier) : ",
        "upsample": "Sur-échantillonner",
        "up_value": "Entrez le taux de sur-échantillonnage (entier) : ",
        "cut_val": "Couper la durée du signal (valeurs)",
        "start_cut": "Entrez le début de la coupure en secondes: ",
        "end_cut": "Entrez la fin de la coupure en secondes: ",
        "valid_cut" : "Entrez des valeurs valides pour la coupure",
        "cut_cursors": "Couper la durée du signal (curseurs)",
        "2pt_cursors": "Sélectionnez 2 points pour couper le signal",
        "move_freq_cursors": "Déplacer la fréquence centrale (curseur)",
        "1pt_cursors": "Sélectionnez 1 point pour sélectionner la fréquence centrale",
        "power_estimate": "Mesures Puissance",
        "psf": "FFT de puissance",
        "mts": "FFT de puissance alternative",
        "mag": "Puissance",
        "estim_peak": "Pic de puissance estimé à :",
        "pseries": "Signal puissance 2 et 4",
        "phase_estimate": "Mesures Phase",
        "diff_phase": "Transitions de phase",
        "diff_freq": "Transitions de fréquence",
        "param_phase_freq": "Lissage de transitions de phase et fréquence",
        "distrib_phase": "Distribution de phase",
        "distrib_freq": "Distribution de fréquence",
        "density": "Densité",
        "insta_phase": "Phase",
        "cyclo_estimate": "Mesures Cyclostationnarité",
        "autocorr": "Autocorrélation rapide",
        "autocorr_full": "Autocorrélation complète",
        "acf_peak": "Recherche automatique d'autocorrélation",
        "acf_peak_txt": "Pic d'autocorrélation détecté à",
        "min_acf_dist": "Distance minimale pour rechercher un pic d'autocorrélation :",
        "ofdm": "Mesures OFDM",
        "ofdm_symbol": "Mesures Symboles OFDM",
        "fft_size": "Changer la taille de la fenêtre FFT",
        "fft_window": "Fenêtre FFT :",
        "freq_xy": "Fréquence",
        "time_xy": "Temps",
        "fc": "Fréquence Centrale",
        "move_txt": "Entrer la correction de FC en Hz (en négatif pour décaler vers la droite) :",
        "confirm_wait" : "Cela peut prendre du temps ou échouer. Continuer?",
        "smoothing_val": "Entrez une valeur de lissage des transitions (désactivé par défaut) :",
        "alpha": "Recherche de l'alpha optimal",
        "estim_tu": "Entrer la valeur estimée de la durée symbole OFDM (en ms, par la fonction d'autocorrélation) :",
        "alpha0": "Entrer le décalage alpha0 en Hz:",
        "ofdm_results": "Caractérisation Sous-Porteuses OFDM",
        "tu": "Temps utile OFDM",
        "tg": "Temps garde OFDM",
        "ts": "Temps utile + garde OFDM",
        "df": "Delta F",
        "alpha_peak": "Pic alpha détecté à :",
        "clock_recovery": "Synchronisation d'horloge de phase",
        "experimental": "EXPERIMENTAL",
        "high_level": "Niveau le plus haut en dB :",
        "low_level": "Niveau le plus bas en dB :",
        "high_freq": "Fréquence à la puissance max",
        "low_freq": "Fréquence à la puissance min",
        "estim_speed": "Estimation de rapidité de modulation par FFT de puissance :",
        "estim_speed_2" : "Estimation alternative de rapidité de modulation - seuil moyen :",
        "estim_speed_3" : "Estimation de rapidité de modulation par signal ^2 et ^4 :",
        "phase_spectrum": "Spectre de phase",
        "bandwidth": "Bande passante",
        "dsp": "Densité Spectrale de Puissance",
        "constellation": "Constellation",
        "define_n": "Entrer la nouvelle valeur de fenêtre FFT :",
        "estim_failed": "Echec de l'estimation de rapidité de modulation. Tentez une autre méthode.",
        "time_estimate": "Mesures Temporelles",
        "freq_estimate": "Mesures Fréquentielles",
        "time_amp": "Temps/Amplitude",
        "persist_spectrum": "Spectre de persistance",
        "spectrogram": "Spectrogramme",
        "smoothing": "Lissage",
        "num_ssp": "Nombre de sous-porteuses",
        "estim_bw": "Estimation de la bande passante :",
        "redef_bw": "Pour redéfinir la bande passante, entrez une nouvelle valeur. Sinon, appuyez sur 'OK'.",
        "unreliable_sscarrier": "L'estimation de position des sous-porteuses est dépendant du calage en fréquence et de la bande passante.",
        "pers_bins": "Nombre de bins pour le spectre de persistance (par défaut 50) :",
        "param_spectre_persistance": "Paramètres du spectre de persistance",
        "save_wav" : "Sauvegarder modifications (nouveau .wav)",
        "peak_find" : "Pic proche curseur",
        "window" : "Fenêtre :",
        "f_resol" : "Résolution en fréquence :",
        "set_window" : "Définir la fonction de fenêtrage",
        "window_choice" : "Choix de la fonction de fenêtrage :",
        "overlap_val" : "Valeur de recouvrement (taille de fenêtre//{nouveau facteur}) :",
        "set_overlap" : "Définir la valeur de recouvrement",
        "dsp_max" : "DSP max",
        "error_stft" : "Erreur dans le calcul de la STFT. Essayez une autre taille de fenêtre, fonction et/ou recouvrement.",
        "freq_adjust" : "Ajustement de fréquence",
        "overlap_valid" : "Entrez une valeur de recouvrement valide",
        "offset_freq" : "Décalage de fréquence",
        "not_apply" : "Pas de moyennage",
        "wav_load" : "Chargement du wav",
        "demod" : "Démodulation",
        "demod_fsk" : "Démodulation CPM/FSK NRZ",
        "demod_psk" : "Démodulation PSK",
        "hist_bins": "Nombre de bins pour les distributions phase/fréquence (par défaut 1000) :",
        "param_hist_bins" : "Paramètres des distributions phase & fréquence",
        "bits_value" : "Symboles",
        "estim_bits" : "Bits démodulés",
        "short_bits" : "(5000 premiers sur le graphe)",
        "bits_fail" : "Echec de la démodulation",
        "demod_param" : "Paramètres de démodulation",
        "param_order" : "Sélectionner l'ordre de modulation",
        "param_order2" : "Ordre 2",
        "param_order4" : "Ordre 4",
        "demod_speed" : "Rapidité de modulation. Entrer 0 pour recherche aveugle",
        "mapping" : "Codage binaire",
        "mapping_nat" : "Naturel",
        "mapping_gray" : "Gray",
        "mapping_custom": "Personnalisé",
        "mapping_custom_desc": "Entrer 4 tuples de bits de plus faible à plus haute fréquence, par exemple (0,0), (0,1), (1,0), (1,1)",
        "clock_frequency" : "Fréquence horloge détectée",
        "center_frq" : "Fréquence centrale",
        "auto_center" : "Correction automatique",
        "filtrer" : "Filtrer signal",
        "window_options" : "Options de fenêtrage",
        "demod_fm" : "Démodulation FM",
        "demod_am" : "Démodulation AM",
        "resample" : "Echantillonnage",
        "cut_signal" : "Découper",
        "audio" : "Lecture audio",
        "wav_conversion": "Erreur de conversion du fichier WAV en signal IQ. Assurez-vous que le fichier est un fichier WAV valide.",
        "unsupported_format": "Format de fichier non pris en charge. Veuillez charger un fichier WAV valide.",
        "median_filter": "Filtre médian",
        "shift_frq": "Décalage Fe/2",
        "kernel_select": "Selectionner taille de noyau: ",
        "kernel_size": "Taille du noyau",
        "kernal_invalid": "Taille de noyau invalide.",
        "light_filter": "Léger",
        "medium_filter": "Moyen",
        "heavy_filter": "Fort",
        "aggressive_filter": "Agressif",
        "dynamic_filter": "Dynamique",
        "kernel_error": "La taille du noyau doit être un entier positif impair.",
        "gaussian_filter": "Filtre gaussien",
        "moving_average": "Moyenne mobile",
        "filter_window": "Fenêtre de filtre",
        "window_size_select" : "Sélectionner taille de fenêtre :",
        "window_invalid" : "Taille de fenêtre invalide.",
        "window_size_error": "La taille de la fenêtre doit être un entier positif.",
        "fir_filter": "Filtre FIR",
        "fir_taps": "Nombre de taps",
        "wiener_filter": "Filtre Wiener",
        "noise_variance": "Variance du bruit",
        "size": "Taille",
        "matched_filter": "Filtre adapté",
        "demod_mfsk": "Démodulation MFSK",
        "mapping_non-binary": "Non-binaire",
        "cyclospectrum": "Cyclospectre",
        "symbol_rate" : "Rapidité de modulation (Bauds)",
        "filter_factor" : "Facteur (0.0-1.0)",
        "pulse_shape" : "Filtre de mise en forme",
        "error_matched_filter" : "Erreur lors de l'application du filtre adapté",
        "estim_speed_4": "Estimation de rapidité de modulation par recherche de fréquence horloge :",
        "mono_real" : "Mono : Réel",
        "mono_iq" : "Mono : IQ",
        "mfsk_discrete_diff" : "Basée sur les transitions de fréquences (méthode NRZ, lissage nécessaire)",
        "mfsk_tone_detection" : "Basée sur la détection des tons (Goertzel - Viterbi)",
        "eye_height": "Hauteur de l'oeil",
        "eye_width": "Largeur de l'oeil",
        "eye_opening_ratio": "Ratio d'ouverture de l'oeil",
        "eye_diagram": "Diagramme de l'oeil",
        "eye_metrics": "Métriques du diagramme de l'oeil",
        "eye_fail": "Echec du tracé du diagramme de l'oeil. Vérifiez la rapidité de modulation et synchronisation du signal.",
        "channel": "Canal",
        "morlet_cwt": "Transformée en ondelettes continues Morlet",
        "scalogram": "Scalogramme (CWT Morlet)",
        "demod_cpm_psk": "Démodulation CPM/FSK & PSK",
        "demod_type": "Sélectionner le type de modulation",
        "more_bits": "bits de plus tronqués",
        "doppler": "Correction décalage Doppler",
        "doppler_txt": "Entrer la valeur de décalage Doppler à corriger en Hz :",
        "param_diff" : "Différentiel",
        "param_offset" : "Décalage 45°",

    }
    return fra_lib

def get_eng_lib():
    # load EN
    eng_lib = {
        "siganto": "SigAnTo : Signal Analysis Tool",
        "lang": "English",
        "load": "Load a WAV file / Restore WAV file",
        "load_msg": "Load a WAV file to start the analysis",
        "close": "Close the WAV file",
        "invalid_wav": "Invalid WAV file",
        "no_file": "No file loaded",
        "encoding": "Encoding: ",
        "samples": "Samples: ",
        "sampling_frq": "Sampling frequency: ",
        "error": "Error",
        "apply": "Apply",
        "debut": "Start",
        "fin": "End",
        "duree": "Duration",
        "oui": "Yes",
        "non": "No",
        "params": "Parameters",
        "main_viz": "Spectrograms",
        "group_spec": "Group: Spectrogram and PSD",
        "spec_dsp": "Spectrogram and PSD",
        "group_const": "Group: Spectrogram, Constellation, PSD max",
        "spec_const": "Spectrogram, Constellation, PSD max",
        "spec_3d": "3D Spectrogram",
        "display": "Display",
        "frq_info": "Frequency/Power/Rate Information",
        "cursors_on": "Cursors: ON",
        "cursors_off": "Cursors: OFF",
        "clear_cursors": "Remove cursors",
        "modify": "Modify",
        "move_frq": "Move center frequency (values)",
        "high_low": "High/Low pass filter",
        "low_val": "Low",
        "high_val": "High",
        "freq_pass": "Cut-off frequency (Hz) :",
        "filter_high_low": "Apply high/low pass filter",
        "bandpass": "Band pass filter",
        "filter_band": "Apply band pass filter",
        "freq_low": "Low cut-off frequency in Hz:",
        "freq_high": "High cut-off frequency in Hz:",
        "freq_valid": "Enter valid cut-off frequencies",
        "mean": "Average signal",
        "mean_level": "Mean level in dB: ",
        "level": "Averaging level: ",
        "apply_mean": "Apply default mean",
        "def_level": "Set threshold",
        "enter_level": "Enter level in dB :",
        "downsample": "Downsample",
        "down_value": "Enter the downsampling ratio (int): ",
        "upsample": "Upsample",
        "up_value": "Enter the upsampling ratio (int): ",
        "cut_val": "Cut length of signal (values)",
        "start_cut": "Enter the start of the cut in seconds: ",
        "end_cut": "Enter the end of the cut in seconds: ",
        "valid_cut" : "Enter valid values for the cut",
        "cut_cursors": "Cut length of signal (cursors)",
        "2pt_cursors": "Select 2 points to cut the signal",
        "1pt_cursors": "Select 1 point to set the center frequency",
        "move_freq_cursors": "Move center frequency (cursor)",
        "power_estimate": "Power Metrics",
        "psf": "Power Spectrum FFT",
        "mts": "Alternative Power Spectrum FFT",
        "mag": "Magnitude",
        "estim_peak": "Estimated power peak at :",
        "pseries": "Power Series FFT",
        "phase_estimate": "Phase Metrics",
        "diff_phase": "Phase Transitions",
        "diff_freq": "Frequency Transitions",
        "param_phase_freq": "Smoothing of Phase and Frequency Transitions",
        "distrib_phase": "Phase Distribution",
        "distrib_freq": "Frequency Distribution",
        "density": "Density",
        "insta_phase": "Phase",
        "cyclo_estimate": "Cyclostationarity Metrics",
        "autocorr": "Fast Autocorrelation",
        "autocorr_full": "Full Autocorrelation",
        "acf_peak": "Autocorrelation Peak Automatic Search",
        "acf_peak_txt": "Autocorrelation peak detected at",
        "min_acf_dist": "Minimum distance to find autocorrelation peaks :",
        "ofdm": "OFDM Metrics",
        "ofdm_symbol": "OFDM Symbol Rate Estimation",
        "fft_size": "Change FFT window size",
        "fft_window": "FFT Window :",
        "freq_xy": "Frequency",
        "time_xy": "Time",
        "fc": "Center Frequency",
        "move_txt": "Enter the CF correction in Hz (negative to shift right) :",
        "confirm_wait" : "This may take some time or fail. Continue?",
        "smoothing_val": "Enter a smoothing value for transitions (disabled by default) :",
        "alpha": "Optimal alpha search",
        "estim_tu": "Enter the estimated OFDM symbol duration value (in ms, from the autocorrelation function) :",
        "alpha0": "Enter the alpha0 offset in Hz :",
        "ofdm_results": "OFDM Parameters Estimation",
        "tu": "OFDM Symbol Duration",
        "tg": "OFDM Guard Duration",
        "ts": "OFDM Symbol + Guard Duration",
        "df": "Delta F",
        "alpha_peak": "Alpha peak detected at :",
        "experimental": "EXPERIMENTAL",
        "high_level": "Highest level in dB :",
        "low_level": "Lowest level in dB :",
        "high_freq": "Frequency at max power",
        "low_freq": "Frequency at min power",
        "estim_speed": "Symbol rate estimation with Power FFT : ",
        "estim_speed_2" : "Alternative symbol rate estimation - mean threshold : ",
        "estim_speed_3" : "Symbol rate estimation with signal ^2 and ^4 : ",
        "phase_spectrum": "Phase Spectrum",
        "bandwidth": "Bandwidth",
        "dsp": "Power Spectral Density",
        "constellation": "Constellation",
        "define_n": "Enter the new FFT window size :",
        "estim_failed": "Symbol rate estimation failed. Try another method.",
        "time_estimate": "Time Metrics",
        "freq_estimate": "Frequency Metrics",
        "time_amp": "Time/Amplitude",
        "persist_spectrum": "Persistence Spectrum",
        "spectrogram": "Spectrogram",
        "smoothing": "Smoothing",
        "num_ssp": "Number of subcarriers",
        "estim_bw": "Bandwidth estimation :",
        "redef_bw": "To redefine the bandwidth, enter a new value. Otherwise, press 'OK'.",
        "unreliable_sscarrier": "Subcarriers position estimation is dependent on frequency offset and bandwidth.",
        "pers_bins": "Number of bins for the persistence spectrum (default 50) :",
        "param_spectre_persistance": "Persistence Spectrum Parameters",
        "save_wav" :"Save signal modifications (new .wav)",
        "peak_find" : "Peak near cursor",
        "window" : "Window :",
        "f_resol" : "Frequency resolution :",
        "set_window" : "Set window function",
        "window_choice" : "Window function choice :",
        "overlap_val" : "Overlap value (window size//{new factor}) :",
        "set_overlap" : "Set overlap value",
        "dsp_max" : "Max PSD",
        "error_stft" : "Error in STFT computation. Try another window size, function and/or overlap.",
        "freq_adjust" : "Frequency fine-tuning",
        "overlap_valid" : "Enter a valid overlap value",
        "offset_freq" : "Frequency offset",
        "not_apply" : "No averaging",
        "wav_load" : "Wav loading",
        "demod" : "Demodulation",
        "demod_fsk" : "CPM/FSK NRZ Demodulation",
        "demod_psk" : "PSK Demodulation",
        "hist_bins": "Number of bins for the phase/frequency distributions (default 1000) :",
        "param_hist_bins": "Phase and Frequency Distribution Parameters",
        "bits_value" : "Symbols",
        "estim_bits" : "Demodulated bits",
        "short_bits" : "(first 5000 bits on the graph)",
        "bits_fail" : "Demodulation failure",
        "demod_param" : "Demodulation parameters",
        "param_order" : "Select modulation order",
        "param_order2" : "2-ary",
        "param_order4" : "4-ary",
        "demod_speed" : "Symbol rate. Enter 0 for blind estimation",
        "mapping" : "Binary ordering",
        "mapping_nat" : "Natural",
        "mapping_gray" : "Gray",
        "mapping_custom": "Custom",
        "mapping_custom_desc": "Enter 4 tuples of bits from lowest to highest frequency, e.g. (0,0), (0,1), (1,0), (1,1)",
        "clock_frequency" : "Detected clock frequency",
        "center_frq" : "Center Frequency",
        "auto_center" : "Automatic offset correction",
        "filtrer" : "Filter signal",
        "window_options" : "Windowing options",
        "demod_fm" : "FM demodulation",
        "demod_am" : "AM demodulation",
        "resample" : "Resample",
        "cut_signal" : "Cut",
        "audio" : "Audio playback",
        "wav_conversion": "Error converting WAV file to IQ signal. Ensure the file is a valid WAV file.",
        "unsupported_format": "Unsupported file format. Please load a valid WAV file.",
        "median_filter": "Median filter",
        "shift_frq": "Fs/2 Shift",
        "kernel_select": "Select kernel size: ",
        "kernel_size": "Kernel size",
        "kernal_invalid": "Invalid kernel size.",
        "light_filter": "Light",
        "medium_filter": "Medium",
        "heavy_filter": "Heavy",
        "aggressive_filter": "Aggressive",
        "dynamic_filter": "Dynamic",
        "kernel_error": "Kernel size must be a positive odd integer.",
        "gaussian_filter": "Gaussian filter",
        "moving_average": "Moving average",
        "filter_window": "Filter window",
        "window_size_select" : "Select window size: ",
        "window_invalid" : "Invalid window size.",
        "window_size_error": "Window size must be a positive integer.",
        "fir_filter": "FIR filter",
        "fir_taps": "Number of taps",
        "wiener_filter": "Wiener filter",
        "noise_variance": "Noise variance",
        "size": "Size",
        "matched_filter": "Matched filter",
        "demod_mfsk": "MFSK Demodulation",
        "mapping_non-binary": "Non-binary",
        "cyclospectrum": "Cyclospectrum FFT",
        "symbol_rate" : "Symbol Rate (Bauds)",
        "filter_factor" : "Factor (0.0-1.0)",
        "pulse_shape" : "Pulse Shaping",
        "error_matched_filter" : "Error when applying the matched filter",
        "estim_speed_4": "Symbol rate estimation with clock frequency detection : ",
        "mono_real" : "Mono : Real",
        "mono_iq" : "Mono : IQ",
        "mfsk_discrete_diff" : "Based on frequency transitions (NRZ method, smoothing necessary)",
        "mfsk_tone_detection" : "Based on tone detection (Goertzel - Viterbi)",
        "eye_height": "Eye Height",
        "eye_width": "Eye Width",
        "eye_opening_ratio": "Eye Opening Ratio",
        "eye_diagram": "Eye Diagram",
        "eye_metrics": "Eye Diagram Metrics",
        "eye_fail": "Eye diagram plotting failed. Check the symbol rate and signal synchronization.",
        "channel": "Channel",
        "morlet_cwt": "Morlet Continuous Wavelet Transform",
        "scalogram": "Scalogram (Morlet CWT)",
        "demod_cpm_psk": "CPM/FSK & PSK Demodulation",
        "demod_type": "Select modulation type",
        "more_bits": "more bits truncated",
        "doppler": "Doppler Offset Correction",
        "doppler_txt": "Enter the Doppler offset value to correct in Hz :",
        "param_diff" : "Differential",
        "param_offset" : "Offset 45°",

    }
    return eng_lib
